name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    defaults:
      run:
        working-directory: ./fun_spec
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Cache Stack dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ghcup
            ~/.cabal/store
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', 'package.yaml', 'stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-stack-
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.6.7"
          stack-version: "2.15.7"

      - name: Build
        run: stack build --coverage
      - name: Run tests
        run: stack test --coverage
      - name: Generate Code Coverage Report
        uses: 8c6794b6/hpc-codecov-action@v4
        with:
          target: stack:p3-test
          format: codecov
          out: coverage.json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
