name: Scan code with HLint
on: [push, pull_request]

jobs:
  hlint:
    defaults:
      run:
        working-directory: ./fun_spec
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to GitHub code scanning.
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-scan@v1

