name: Formatting workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ormolu:
    defaults:
      run:
        working-directory: ./fun_spec
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: haskell-actions/run-ormolu@v14
        with:
          mode: inplace
      - name: apply formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ always() }}
        with:
          commit_message: automated ormolu commit
